### ISSUE TITLE
Serve plugins with nginx?

### ISSUE THREAD

**Issue by pierreozoux** [0ex/discourse-kiss#3]
Something I didn't understand, how do you serve plugi/ compiled assets from nginx?

as they don't share any volumes in your setup..

I'm curious, I saw your post from discourse.

I maintained this since many years, and it is a pain...

https://lab.libreho.st/libre.sh/docker/discourse/
https://lab.libreho.st/libre.sh/docker/discourse-web/

Maybe we can collaborate :+1: 

cheers!

**Comment by akvadrako** [comment]
Hi Pierre :)

The method I went for is using nginx as a cache. So the first request is passed to unicorn, then the asset will be returned by nginx. At least that's the idea; I didn't verify the cache is actually being used.

I am quite open to collaboration. I don't use discourse heavily so my main concern is keeping the maintenance burden low.

**Comment by pierreozoux** [comment]
Thanks for your answer :)

I'll come back when I have a more concrete idea around collaboration, but first I have to finish s3 support for my containers.

cheers!
